name: kids_space_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.13.0
  get_it: ^7.7.0
  mobx: ^2.5.0
  flutter_secure_storage: ^8.0.0
  cloud_firestore: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: any
  mobx_codegen: any

flutter:
  uses-material-design: true
